"""Evaluate ranking configs with precision@5 / @10 over the labeled evaluation resumes.

Every number in the README's results table comes from this script's output (data/eval/results.md).

    python scripts/eval_pool.py     # list roles that still need labels
    python scripts/evaluate.py
"""

import statistics
import sys

from jobforge.config import get_settings
from jobforge.db import connect
from jobforge.evaluation import (CONFIGS, EVAL_DIR, build_pool, label_key, load_labels, load_resumes,
                                 precision_at_k, ranked_keys)
from jobforge.explain import explain_matches, make_llm, ungrounded_skills
from jobforge.match import DEFAULT_PRIOR, DEFAULT_W_SEM, load_descriptions, rank
from jobforge.skills import SkillExtractor, load_vocab

GROUNDING_SAMPLE = 50


def main() -> int:
    labels, resumes, extractor = load_labels(), load_resumes(), SkillExtractor(load_vocab())
    with connect() as conn:
        pools = [build_pool(conn, name, text, extractor) for name, text in resumes.items()]

        # --- ranking quality ---
        table, missing = [], set()
        for config in CONFIGS:
            p5, p10 = [], []
            for pool in pools:
                rel = []
                for key in ranked_keys(pool, config):
                    label = labels.get((pool.resume, *key))
                    if label is None:
                        missing.add((pool.resume, *key))
                    rel.append(bool(label))
                p5.append(precision_at_k(rel, 5))
                p10.append(precision_at_k(rel, 10))
            table.append((config.name, statistics.mean(p5), statistics.mean(p10)))
        if missing:
            print(f"{len(missing)} ranked roles have no label; run scripts/eval_pool.py and label them.", file=sys.stderr)
            return 1

        # Base rate: how many roles in each pool are relevant, regardless of order
        pool_rate = statistics.mean(
            statistics.mean(labels[(p.resume, *key)] for key in {label_key(c["company"], c["title"]) for c in p.candidates})
            for p in pools)

        # --- explanation grounding ---
        settings = get_settings()
        llm = make_llm(settings)
        explained, checked = [], 0
        for pool in pools:
            top = rank(pool.candidates, pool.skills, pool.resume_skills, DEFAULT_W_SEM, 5, DEFAULT_PRIOR)
            descriptions = load_descriptions(conn, [r["job_id"] for r in top])
            explained += explain_matches(top, descriptions, resumes[pool.resume], extractor, llm=llm,
                                         model_name=settings.llm_model or "", cache=None)
        sample = explained[:GROUNDING_SAMPLE]
        by_source = {}
        for m in sample:
            ok = not ungrounded_skills(m["explanation"], m, extractor)
            by_source.setdefault(m["explanation_source"], []).append(ok)
            checked += 1

    best = max(table, key=lambda r: (r[1], r[2]))
    lines = [
        "# Evaluation results",
        "",
        f"Generated by `scripts/evaluate.py`. {len(pools)} synthetic resumes; each re-ranks the same "
        f"top-{len(pools[0].candidates)} semantic candidate pool, fully labeled ({len(labels)} role labels, "
        f"assigned by Claude per `data/eval/LABELING.md`, not yet reviewed by a person).",
        "",
        "| Ranking | Precision@5 | Precision@10 |",
        "|---|---|---|",
        *[f"| {name}{' **(best)**' if name == best[0] else ''} | {p5:.3f} | {p10:.3f} |" for name, p5, p10 in table],
        "",
        f"Share of relevant roles in the candidate pools (any ordering): {pool_rate:.3f}.",
        "",
        "## Explanation grounding",
        "",
        f"Sample: the first {checked} top-5 explanations. Grounded = names no skill outside the match's "
        "matched/missing lists (checked with the PhraseMatcher).",
        "",
        "| Source | Explanations | Grounded |",
        "|---|---|---|",
        *[f"| {src} | {len(oks)} | {sum(oks) / len(oks):.0%} |" for src, oks in sorted(by_source.items())],
    ]
    if "llm" not in by_source:
        lines += ["", "LLM explanations were not measured: no LLM is configured in `.env`."]
    out = EVAL_DIR / "results.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    print(f"\nWrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
