"""Extract skills for every job into job_skills: PhraseMatcher first, then filtered KeyBERT keywords.

By default only jobs with no job_skills rows are processed, so reruns are cheap and idempotent.
After editing data/skills.csv, rerun with --rebuild to recompute everything (job_skills is
derived data, fully regenerated by this script).

    python scripts/extract_skills.py
    python scripts/extract_skills.py --rebuild
    python scripts/extract_skills.py --no-keybert
"""

import argparse
import statistics
import time
from collections import Counter

from keybert import KeyBERT
from sklearn.feature_extraction.text import CountVectorizer

from jobforge.db import connect
from jobforge.embed import get_model
from jobforge.skills import SkillExtractor, filter_candidates, load_vocab, mentions_company

INSERT_SQL = "INSERT INTO job_skills (job_id, skill, method) VALUES (%s, %s, %s) ON CONFLICT DO NOTHING"
KEYBERT_TOP_N = 5
CHUNK = 1000


def job_text(title: str, description: str) -> str:
    return f"{title}\n{description}"


def phrase_match(extractor: SkillExtractor, jobs: list[tuple]) -> list[tuple[int, str, str]]:
    rows = []
    for (job_id, company, title, desc), skills in zip(jobs, extractor.extract_many([job_text(t, d) for _, _, t, d in jobs])):
        # A company's own product name ("Databricks" at Databricks) is the employer, not a requirement
        rows += [(job_id, s, "phrase_match") for s in sorted(skills) if s.lower() != company.lower()]
    return rows


def keybert(extractor: SkillExtractor, jobs: list[tuple], corpus: list[str]) -> list[tuple[int, str, str]]:
    # Candidates come from the whole corpus: min_df drops one-off phrases, max_df drops generic ones
    cv = CountVectorizer(ngram_range=(1, 2), stop_words="english", min_df=10, max_df=0.3).fit(corpus)
    candidates = filter_candidates(list(cv.get_feature_names_out()), extractor.vocab, extractor.nlp)
    fixed = CountVectorizer(ngram_range=(1, 2), vocabulary=candidates)
    print(f"KeyBERT: {len(cv.vocabulary_)} corpus phrases -> {len(candidates)} candidates after filtering")

    model = get_model()
    kw = KeyBERT(model=model)
    word_emb = model.encode(list(fixed.get_feature_names_out()), batch_size=256)  # once, shared by all chunks
    rows = []
    for i in range(0, len(jobs), CHUNK):
        chunk = jobs[i:i + CHUNK]
        docs = [job_text(t, d) for _, _, t, d in chunk]
        results = kw.extract_keywords(docs, vectorizer=fixed, top_n=KEYBERT_TOP_N * 3, use_mmr=True,
                                      diversity=0.5, doc_embeddings=model.encode(docs, batch_size=64),
                                      word_embeddings=word_emb)
        if len(docs) == 1:
            results = [results]
        for (job_id, company, _, _), keywords in zip(chunk, results):
            kept = [k for k, _ in keywords if not mentions_company(k, company)][:KEYBERT_TOP_N]
            rows += [(job_id, k, "keybert") for k in kept]
        print(f"  {min(i + CHUNK, len(jobs))}/{len(jobs)} jobs")
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--rebuild", action="store_true", help="delete all job_skills and recompute")
    parser.add_argument("--no-keybert", action="store_true", help="PhraseMatcher only")
    args = parser.parse_args()

    with connect(vector=False) as conn:
        if args.rebuild:
            conn.execute("DELETE FROM job_skills")
        all_jobs = conn.execute("SELECT id, company, title, description FROM jobs ORDER BY id").fetchall()
        done = {r[0] for r in conn.execute("SELECT DISTINCT job_id FROM job_skills")}
        jobs = [j for j in all_jobs if j[0] not in done]
        print(f"{len(jobs)} jobs to process ({len(done)} already have skills)")
        if not jobs:
            return

        extractor = SkillExtractor(load_vocab())
        t = time.time()
        rows = phrase_match(extractor, jobs)
        print(f"PhraseMatcher: {len(rows)} skills in {time.time() - t:.0f}s")
        if not args.no_keybert:
            t = time.time()
            rows += keybert(extractor, jobs, [job_text(t, d) for _, _, t, d in all_jobs])
            print(f"KeyBERT done in {time.time() - t:.0f}s")

        with conn.cursor() as cur:
            cur.executemany(INSERT_SQL, rows)

        per_job = Counter(job_id for job_id, _, m in rows if m == "phrase_match")
        counts = [per_job.get(j[0], 0) for j in jobs]
        print(f"\nPhrase-matched skills per job: median {statistics.median(counts):.0f}, "
              f">=5 skills: {sum(c >= 5 for c in counts) / len(counts):.0%}, none: {counts.count(0)}")
        top_kb = Counter(s for _, s, m in rows if m == "keybert").most_common(20)
        if top_kb:
            print("Most common KeyBERT keywords (candidates for data/skills.csv):")
            print("  " + ", ".join(f"{s} ({n})" for s, n in top_kb))


if __name__ == "__main__":
    main()
